#!/usr/bin/env bash


alt=$(       tput smcup    || tput ti ) # Start alt display
ealt=$(      tput rmcup    || tput te ) # End alt display
bold=$(      tput bold     || tput md ) # Start bold
stout=$(     tput smso     || tput so ) # Start stand-out
estout=$(    tput rmso     || tput se ) # End stand-out
under=$(     tput smul     || tput us ) # Start underline
eunder=$(    tput rmul     || tput ue ) # End underline
reset=$(     tput sgr0     || tput me ) # Reset cursor
blink=$(     tput blink    || tput mb ) # Start blinking
black=$(     tput setaf 0  || tput AF 0 )
red=$(       tput setaf 1  || tput AF 1 )
green=$(     tput setaf 2  || tput AF 2 )
yellow=$(    tput setaf 3  || tput AF 3 )
blue=$(      tput setaf 4  || tput AF 4 )
magenta=$(   tput setaf 5  || tput AF 5 )
cyan=$(      tput setaf 6  || tput AF 6 )
white=$(     tput setaf 7  || tput AF 7 )
bblack=$(    tput setaf 8  || tput AF 8 )
bred=$(      tput setaf 9  || tput AF 9 )
bgreen=$(    tput setaf 10 || tput AF 10 )
byellow=$(   tput setaf 11 || tput AF 11 )
bblue=$(     tput setaf 12 || tput AF 12 )
bmagenta=$(  tput setaf 13 || tput AF 13 )
bcyan=$(     tput setaf 14 || tput AF 14 )
bwhite=$(    tput setaf 15 || tput AF 15 )


