#!/usr/bin/env bash

DOTFILES_DIR="${HOME}/.dotfiles"

cd ${DOTFILES_DIR}

link() {
  # Force create/replace the symlink
  ln -fs "${DOTFILES_DIR}/${1}" "${HOME}/${1}"
}

link ".bash_aliases"
link ".bash_profile"
link ".bash_prompt"
link ".bashrc"
link ".brewfile"
link ".dircolors"
link ".editorconfig"
link ".exports"
link ".functions"
link ".hushlogin"
link ".inputrc"

echo "Dotfiles update complete!"
