#!/usr/bin/env bash

DOTFILES_DIR="${HOME}/.dotfiles"
LOCAL_DOTFILES="${HOME}/.dotfiles.local"

link() {
  # Force create/replace the symlink
  ln -fs "${DOTFILES_DIR}/${1}" "${HOME}/${1}"
}

# add a check to see if directory exists first
cd ${DOTFILES_DIR}

link ".bash_aliases"
link ".bash_profile"
link ".bash_prompt"
link ".bashrc"
link "Brewfile"
link ".dircolors"
link ".editorconfig"
link ".exports"
link ".functions"
link ".hushlogin"
link ".inputrc"
link ".fzf.bash"
link ".fzf.zsh"
link ".zshrc"

# add a check to see if directory exists first
cd ${LOCAL_DOTFILES}

ln -fs ~/.dotfiles.local/.env ~/.env
ln -fs ~/.dotfiles.local/.gitconfig.local ~/.gitconfig.local

echo "Dotfiles update complete!"
